### PR TITLE
Fix cross repo

### LINKED ISSUE #23: Cross-repo bug 2
It looks like cross-repo is still not working for example: 

https://github.com/ubiquity-os-marketplace/.ubiquity-os/pull/17 is linking to `ubiquity-os/.github#6` but the plugin used https://github.com/ubiquity-os-marketplace/.ubiquity-os/pull/6 as the linked issue. It appears the number is correct but the owner and repo are not correct.

### PR DESCRIPTION
**Pull request by whilefoo**
Resolves #23 

QA
PR: https://github.com/ubiquibot-whilefoo-testing/testing/pull/32#pullrequestreview-2685609117
Action run: https://github.com/ubiquity-whilefoo/daemon-pull-review/actions/runs/13857887680/job/38778757220

### CODE REVIEW

**Comment by gentlementlegen** [comment]
Thanks for the fix. I noticed in the bot comment that there is not metadata at all, which doesn't help for debugging? is this plugin not using the SDK to post comments at all?

File: src/handlers/pull-reviewer.ts [hunk 1]
```diff
@@ -307,37 +298,41 @@ export class PullReviewer {
...
-      throw this.context.logger.error("Task number not found", { pull_request });
+      throw logger.error("Task number not found", { pull_request });
     }
 
     const issues = (await Promise.all(
       closingIssues.map(async (issue) => {
         const issueNumber = issue.number;
         const issueRepo = issue.repository.name;
-        const issueOwner = issue.repository.owner;
+        const issueOwner = issue.repository.owner.login;
```
Comment (0x4007) [inline src/handlers/pull-reviewer.ts:329]: This looks like the only main difference is this sufficient?

**Review by 0x4007 — APPROVED** [review]
Change all the cautions to warnings please as per what I've been saying for weeks

**Comment by 0x4007** [comment]
> Warning
> 
> This task does not reflect a business priority at the moment. You may start tasks with one of the following labels: `Priority: 1 (Normal)`, `Priority: 2 (Medium)`, `Priority: 3 (High)`, `Priority: 4 (Urgent)`, `Priority: 5 (Emergency)`

I guess in this situation it shouldn't close the pull. Seems a bit abrasive.

**Comment by gentlementlegen** [comment]
@0x4007 I think closing the pr makes it clear to contributors that the task is not for them to take, otherwise they would keep working on it. Also, that would make us manually close them before rewards.

File: src/handlers/pull-reviewer.ts [hunk 2]
```diff
@@ -118,10 +118,10 @@ export class PullReviewer {
    */
   async submitCodeReview(review: string | undefined, status: CodeReviewStatus): Promise<void> {
     const { logger, payload } = this.context;
-    const { number, organization, repository, action, sender } = payload;
```
Comment (gentlementlegen) [inline src/handlers/pull-reviewer.ts:121]: Was `organization` targeting the org where the action originated from instead of the actual linked pull-request repo, am I understanding this right?

**Comment by gentlementlegen** [comment]
Tested with a few different PRs from cross repos, sorry if it is unclear I was testing locally as I don't have any more credits: https://github.com/Meniole/daemon-pull-review/pull/10#issuecomment-2726428182

Seems to use the proper target.

File: src/handlers/pull-reviewer.ts (hunk 1 above)
Comment (gentlementlegen) [reply src/handlers/pull-reviewer.ts:329]: I actually don't understand how this could work before, `owner` is an object and it is passed below in `fetchIssue` which expects a string.

**Review by gentlementlegen — APPROVED** [review]
Fine with the changes, please address my comments.

File: src/handlers/pull-reviewer.ts (hunk 1 above)
Comment (whilefoo) [reply src/handlers/pull-reviewer.ts:329]: The actual problem was that types were wrong:
https://github.com/ubiquity-os-marketplace/daemon-pull-review/pull/24/files#diff-5058006e565bba46a5a276941c431bee998444e0db6d2439d88c5d3c878d8ec2L286-L287
https://github.com/ubiquity-os-marketplace/daemon-pull-review/pull/24/files#diff-03d3772154bc344b639b231a8ce91527d0fe30853e2dde652fa9d9ea29c081d0L4-L5
so `issueRepo` and `issueOwner` were undefined and `fetchIssue` uses payload's repo if the params are undefined

File: src/handlers/pull-reviewer.ts (hunk 2 above)
Comment (whilefoo) [reply src/handlers/pull-reviewer.ts:121]: it had nothing to do with `organization`, that was just to fix the log which used `organization` which is an object not a string

**Comment by whilefoo** [comment]
> Change all the cautions to warnings please as per what I've been saying for weeks

All? I found only one case where it would be suitable to change to warning

File: src/handlers/pull-reviewer.ts (hunk 2 above)
Comment (gentlementlegen) [reply src/handlers/pull-reviewer.ts:121]: What difference is there with `${organization}/${repository}#${number}` and `${repository.owner.login}/${repository.name}#${number}`, I guess the later also works for individual repo, not only organizations?

Comment (whilefoo) [reply src/handlers/pull-reviewer.ts:121]: `organization` and `repository` are objects so the result was `[object Object]/[object Object]#32`. But otherwise yes, I removed `organization` in favor of `repository.owner` because it will work for individual repos

**Comment by 0x4007** [comment]
> > Change all the cautions to warnings please as per what I've been saying for weeks
> 
> 
> 
> All? I found only one case where it would be suitable to change to warning

Caution where we need to triage. Warning for all user errors

**Comment by gentlementlegen** [comment]
Wouldn't it make sense to use `fatal` for triage and `error` for errors?

**Comment by 0x4007** [comment]
To be more precise it would make a lot more sense to rename the methods as `clientError` and `serverError` as I proposed many times. 

I didn't think error and fatal would be so subjective but as I understand everybody keeps making it render as caution.

**Comment by whilefoo** [comment]
> Caution where we need to triage. Warning for all user errors

Yes, only 1 was suitable to change

> To be more precise it would make a lot more sense to rename the methods as `clientError` and `serverError` as I proposed many times.

We can try that but it feels so unnatural for logger to have `clientError` and `serverError` but I think the root problem is trying to combine a logger and comment handler (`TIP` and `IMPORTANT` don't belong to a logger)

**Comment by gentlementlegen** [comment]
Why not adding a capability to the SDK that would do the triage on fatal errors instead? This capability does not belong to a logger package.

**Comment by 0x4007** [comment]
I'm open to the triage logic being elsewhere but the idea is that we'll be able to focus our attention immediately on bug fixes. We can also dynamically prioritize based on the amount of hits a bug gets.
